### PR TITLE
Fix average

### PR DESCRIPTION
**Pull request by atrelinski**
I am NOT convinced that this is good fix, because it doesn't take into account that samples can be collected in non-const interval.
It just fix problem for very short builds => see print screen.
Maybe even better fix is needed - reject merging if You think this fix is not enough.

### CODE REVIEW

**Comment by KrzysztofBuchacz** [comment]
This is bad idea. You cannot assume tick are collected in regular way. Usage diagram is drawn as set of trapezoids, you need at least two ticks to show somethimg. If numer of ticks is less than 2 average value shouldn't be displayed. That's why I collected ticks on Begin and End of build - to have at least two ticks even for very short builds.


So:
- Do not show Avg value if no diagram is visible
- Aviod divide by zero sumTicks

**Comment by KrzysztofBuchacz** [comment]
Iteresting fact: after 1 minute of build I should have 60 ticks but under debugger I see 29. I cannot explain this.

**Comment by KrzysztofBuchacz** [comment]
image
Divide by zero occurs also during resize

**Comment by atrelinski** [comment]
> Iteresting fact: after 1 minute of build I should have 60 ticks but under debugger I see 29. I cannot explain this.
Since I fixed event function assignment, I don't observe any problems with number of calls over time. To debug this I put break point at closing bracket in DataModel.BuildDone() method.

**Comment by KrzysztofBuchacz** [comment]
I have very slow machine, notebook with 2 cores, and ticks are longer than 1 s and not regular, , 
		[53]	1.02825022	float
		[54]	1.01428735	float
		[55]	1.01927316	float
		[56]	1.01029658	float
		[57]	1.01129544	float
		[58]	1.01329041	float
		[59]	1.00431454	float
		[60]	1.019274	float
		[61]	1.00131965	float
		[62]	1.00830364	float
		[63]	1.01528561	float
		[64]	1.00431275	float
		[65]	1.0152837	float
		[66]	0.9983299	float
		[67]	1.01229262	float
		[68]	1.00032508	float
		[69]	1.00032318	float
		[70]	1.006309	float
		[71]	1.01129484	float

**Comment by atrelinski** [comment]
I just find out warning about classes that have PerformanceCounters does
not implement IDisposable interface.
Maybe counters should be released after use?

**Pull request closed without merging**
